#pragma once

enum OBJID {PLAYER, BULLET , HACK, RAZER, MONSTER, MONSTER_BULLET, BOSS, MONSTER2,MONSTER3,MONSTER4, YHMONSTER, MONSTERBULLET, OBJ_END};

enum SCENEID {
	START,
	STAGE1,
	STAGE2,
	STAGE3,
	ENDING,
	SCENE_END,
};